"""add lookup_token

Revision ID: 4ad4f3ccbb3c
Revises: 81b7f015b38c
Create Date: 2026-04-19 18:03:35.719621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad4f3ccbb3c'
down_revision = '81b7f015b38c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lookup_token', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_visit_lookup_token'), ['lookup_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visit_lookup_token'))
        batch_op.drop_column('lookup_token')

    # ### end Alembic commands ###
