"""update new database1 

Revision ID: 81b7f015b38c
Revises: 
Create Date: 2026-04-12 12:43:46.473536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81b7f015b38c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
       # batch_op.create_foreign_key(None, 'patient', ['patient_name'], ['name'])
       pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
       # batch_op.drop_constraint(None, type_='foreignkey')
        pass 
    # ### end Alembic commands ###
